"""
Generates data/agri/questions.json: the AgriIndia pilot benchmark.

40 questions, each in English, Hindi, Telugu and Hinglish, with one gold SQL
query. Categories:
  agg     - single aggregate with filters (often 2-3 joins)
  count   - counting rows
  group   - per-category aggregate (needs GROUP BY)   <- IndicDB's 28% failure mode
  topk    - per-category aggregate + ORDER BY + LIMIT  (also needs GROUP BY)

Every gold SQL is executed by tests/test_benchmark.py and must return rows.
Top-k questions explicitly ask for the value too ("...and how much?") so that a
correct answer has a single unambiguous column set.

NOTE: Hindi/Telugu/Hinglish wording was written for this pilot and should be
reviewed by native speakers before results are reported in the final paper.

    python scripts/make_agri_questions.py
"""
import json
import os

P = "crop_production p"
ST = "JOIN districts d ON p.district_id = d.district_id JOIN states s ON d.state_id = s.state_id"
CR = "JOIN crops c ON p.crop_id = c.crop_id"
CAT = CR + " JOIN crop_categories cc ON c.category_id = cc.category_id"
SE = "JOIN seasons se ON p.season_id = se.season_id"

Q = [
    # ---------------- agg: single aggregate ----------------
    dict(cat="agg",
         en="What was the total rice production in Punjab in 2015?",
         hi="2015 में पंजाब में चावल का कुल उत्पादन कितना था?",
         te="2015లో పంజాబ్‌లో వరి మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2015 mein Punjab mein rice ka total production kitna tha?",
         sql=f"SELECT SUM(p.production_quantity) FROM {P} {CR} {ST} WHERE c.crop_name = 'Rice' AND s.state_name = 'Punjab' AND p.year = 2015"),
    dict(cat="agg",
         en="What was the total area under wheat in Uttar Pradesh in 2015, in hectares?",
         hi="2015 में उत्तर प्रदेश में गेहूं की खेती का कुल क्षेत्रफल कितने हेक्टेयर था?",
         te="2015లో ఉత్తర ప్రదేశ్‌లో గోధుమ సాగు మొత్తం విస్తీర్ణం ఎన్ని హెక్టార్లు?",
         hinglish="2015 mein Uttar Pradesh mein wheat ka total area kitne hectare tha?",
         sql=f"SELECT SUM(p.area_hectares) FROM {P} {CR} {ST} WHERE c.crop_name = 'Wheat' AND s.state_name = 'Uttar Pradesh' AND p.year = 2015"),
    dict(cat="agg",
         en="What was the average yield per hectare of wheat in Haryana in 2015?",
         hi="2015 में हरियाणा में गेहूं की प्रति हेक्टेयर औसत उपज कितनी थी?",
         te="2015లో హర్యానాలో గోధుమ సగటు దిగుబడి హెక్టారుకు ఎంత?",
         hinglish="2015 mein Haryana mein wheat ki average yield kitni thi?",
         sql=f"SELECT AVG(p.yield_per_hectare) FROM {P} {CR} {ST} WHERE c.crop_name = 'Wheat' AND s.state_name = 'Haryana' AND p.year = 2015"),
    dict(cat="agg",
         en="What was the total sugarcane production in Maharashtra in 2018?",
         hi="2018 में महाराष्ट्र में गन्ने का कुल उत्पादन कितना था?",
         te="2018లో మహారాష్ట్రలో చెరకు మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2018 mein Maharashtra mein sugarcane ka total production kitna tha?",
         sql=f"SELECT SUM(p.production_quantity) FROM {P} {CR} {ST} WHERE c.crop_name = 'Sugarcane' AND s.state_name = 'Maharashtra' AND p.year = 2018"),
    dict(cat="agg",
         en="What was the highest yield per hectare recorded for maize in Karnataka in 2015?",
         hi="2015 में कर्नाटक में मक्का की सबसे अधिक दर्ज प्रति हेक्टेयर उपज कितनी थी?",
         te="2015లో కర్ణాటకలో మొక్కజొన్నకు నమోదైన గరిష్ఠ దిగుబడి హెక్టారుకు ఎంత?",
         hinglish="2015 mein Karnataka mein maize ki sabse zyada yield kitni record hui?",
         sql=f"SELECT MAX(p.yield_per_hectare) FROM {P} {CR} {ST} WHERE c.crop_name = 'Maize' AND s.state_name = 'Karnataka' AND p.year = 2015"),
    dict(cat="agg",
         en="What was the total cotton production in Gujarat in 2015?",
         hi="2015 में गुजरात में कपास का कुल उत्पादन कितना था?",
         te="2015లో గుజరాత్‌లో పత్తి మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2015 mein Gujarat mein cotton ka total production kitna tha?",
         sql=f"SELECT SUM(p.production_quantity) FROM {P} {CR} {ST} WHERE c.crop_name = 'Cotton(Lint)' AND s.state_name = 'Gujarat' AND p.year = 2015"),
    dict(cat="agg",
         en="What was the total wheat production in the Rabi season in Madhya Pradesh in 2015?",
         hi="2015 में मध्य प्रदेश में रबी मौसम में गेहूं का कुल उत्पादन कितना था?",
         te="2015లో మధ్యప్రదేశ్‌లో రబీ సీజన్‌లో గోధుమ మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2015 mein Madhya Pradesh mein Rabi season mein wheat ka total production kitna tha?",
         sql=f"SELECT SUM(p.production_quantity) FROM {P} {CR} {ST} {SE} WHERE c.crop_name = 'Wheat' AND s.state_name = 'Madhya Pradesh' AND se.season_name = 'Rabi' AND p.year = 2015"),
    dict(cat="agg",
         en="What was the total potato production in West Bengal in 2015?",
         hi="2015 में पश्चिम बंगाल में आलू का कुल उत्पादन कितना था?",
         te="2015లో పశ్చిమ బెంగాల్‌లో బంగాళాదుంప మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2015 mein West Bengal mein potato ka total production kitna tha?",
         sql=f"SELECT SUM(p.production_quantity) FROM {P} {CR} {ST} WHERE c.crop_name = 'Potato' AND s.state_name = 'West Bengal' AND p.year = 2015"),
    dict(cat="agg",
         en="What was the average yield per hectare of groundnut in Gujarat in 2015?",
         hi="2015 में गुजरात में मूंगफली की प्रति हेक्टेयर औसत उपज कितनी थी?",
         te="2015లో గుజరాత్‌లో వేరుశనగ సగటు దిగుబడి హెక్టారుకు ఎంత?",
         hinglish="2015 mein Gujarat mein groundnut ki average yield kitni thi?",
         sql=f"SELECT AVG(p.yield_per_hectare) FROM {P} {CR} {ST} WHERE c.crop_name = 'Groundnut' AND s.state_name = 'Gujarat' AND p.year = 2015"),
    dict(cat="agg",
         en="What was the total rice production in Telangana in 2018?",
         hi="2018 में तेलंगाना में चावल का कुल उत्पादन कितना था?",
         te="2018లో తెలంగాణలో వరి మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2018 mein Telangana mein rice ka total production kitna tha?",
         sql=f"SELECT SUM(p.production_quantity) FROM {P} {CR} {ST} WHERE c.crop_name = 'Rice' AND s.state_name = 'Telangana' AND p.year = 2018"),

    # ---------------- count ----------------
    dict(cat="count",
         en="How many districts are there in Bihar?",
         hi="बिहार में कितने जिले हैं?",
         te="బీహార్‌లో ఎన్ని జిల్లాలు ఉన్నాయి?",
         hinglish="Bihar mein kitne districts hain?",
         sql="SELECT COUNT(*) FROM districts d JOIN states s ON d.state_id = s.state_id WHERE s.state_name = 'Bihar'"),
    dict(cat="count",
         en="How many crops are in the Pulses category?",
         hi="दालों की श्रेणी में कितनी फसलें हैं?",
         te="పప్పుధాన్యాల వర్గంలో ఎన్ని పంటలు ఉన్నాయి?",
         hinglish="Pulses category mein kitni crops hain?",
         sql="SELECT COUNT(*) FROM crops c JOIN crop_categories cc ON c.category_id = cc.category_id WHERE cc.category_name = 'Pulses'"),
    dict(cat="count",
         en="How many states are there in the database?",
         hi="डेटाबेस में कितने राज्य हैं?",
         te="డేటాబేస్‌లో ఎన్ని రాష్ట్రాలు ఉన్నాయి?",
         hinglish="Database mein kitne states hain?",
         sql="SELECT COUNT(*) FROM states"),
    dict(cat="count",
         en="How many districts does Telangana have?",
         hi="तेलंगाना में कितने जिले हैं?",
         te="తెలంగాణలో ఎన్ని జిల్లాలు ఉన్నాయి?",
         hinglish="Telangana mein kitne districts hain?",
         sql="SELECT COUNT(*) FROM districts d JOIN states s ON d.state_id = s.state_id WHERE s.state_name = 'Telangana'"),

    # ---------------- group: needs GROUP BY ----------------
    dict(cat="group",
         en="For each state, what was the total rice production in 2015?",
         hi="2015 में हर राज्य के लिए चावल का कुल उत्पादन कितना था?",
         te="2015లో ప్రతి రాష్ట్రానికి వరి మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2015 mein har state ke liye rice ka total production kitna tha?",
         sql=f"SELECT s.state_name, SUM(p.production_quantity) FROM {P} {CR} {ST} WHERE c.crop_name = 'Rice' AND p.year = 2015 GROUP BY s.state_name"),
    dict(cat="group",
         en="For each season, what was the total area under rice in Odisha in 2015?",
         hi="2015 में ओडिशा में हर मौसम के लिए चावल का कुल क्षेत्रफल कितना था?",
         te="2015లో ఒడిశాలో ప్రతి సీజన్‌కు వరి మొత్తం విస్తీర్ణం ఎంత?",
         hinglish="2015 mein Odisha mein har season ke liye rice ka total area kitna tha?",
         sql=f"SELECT se.season_name, SUM(p.area_hectares) FROM {P} {CR} {ST} {SE} WHERE c.crop_name = 'Rice' AND s.state_name = 'Odisha' AND p.year = 2015 GROUP BY se.season_name"),
    dict(cat="group",
         en="For each crop category, what was the total cultivated area in Tamil Nadu in 2015?",
         hi="2015 में तमिलनाडु में हर फसल श्रेणी के लिए कुल खेती का क्षेत्रफल कितना था?",
         te="2015లో తమిళనాడులో ప్రతి పంట వర్గానికి మొత్తం సాగు విస్తీర్ణం ఎంత?",
         hinglish="2015 mein Tamil Nadu mein har crop category ke liye total area kitna tha?",
         sql=f"SELECT cc.category_name, SUM(p.area_hectares) FROM {P} {CAT} {ST} WHERE s.state_name = 'Tamil Nadu' AND p.year = 2015 GROUP BY cc.category_name"),
    dict(cat="group",
         en="For each year from 2010 onwards, what was the total wheat production in Punjab?",
         hi="2010 से आगे हर वर्ष के लिए पंजाब में गेहूं का कुल उत्पादन कितना था?",
         te="2010 నుండి ప్రతి సంవత్సరానికి పంజాబ్‌లో గోధుమ మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2010 se har year ke liye Punjab mein wheat ka total production kitna tha?",
         sql=f"SELECT p.year, SUM(p.production_quantity) FROM {P} {CR} {ST} WHERE c.crop_name = 'Wheat' AND s.state_name = 'Punjab' AND p.year >= 2010 GROUP BY p.year"),
    dict(cat="group",
         en="For each district of Telangana, what was the total rice production in 2018?",
         hi="2018 में तेलंगाना के हर जिले के लिए चावल का कुल उत्पादन कितना था?",
         te="2018లో తెలంగాణలోని ప్రతి జిల్లాకు వరి మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2018 mein Telangana ke har district ke liye rice ka total production kitna tha?",
         sql=f"SELECT d.district_name, SUM(p.production_quantity) FROM {P} {CR} {ST} WHERE c.crop_name = 'Rice' AND s.state_name = 'Telangana' AND p.year = 2018 GROUP BY d.district_name"),
    dict(cat="group",
         en="For each crop, what was the average yield per hectare in Punjab in 2015?",
         hi="2015 में पंजाब में हर फसल के लिए प्रति हेक्टेयर औसत उपज कितनी थी?",
         te="2015లో పంజాబ్‌లో ప్రతి పంటకు సగటు దిగుబడి హెక్టారుకు ఎంత?",
         hinglish="2015 mein Punjab mein har crop ke liye average yield kitni thi?",
         sql=f"SELECT c.crop_name, AVG(p.yield_per_hectare) FROM {P} {CR} {ST} WHERE s.state_name = 'Punjab' AND p.year = 2015 GROUP BY c.crop_name"),
    dict(cat="group",
         en="For each state, what was the total area under pulses in 2015?",
         hi="2015 में हर राज्य के लिए दालों का कुल क्षेत्रफल कितना था?",
         te="2015లో ప్రతి రాష్ట్రానికి పప్పుధాన్యాల మొత్తం విస్తీర్ణం ఎంత?",
         hinglish="2015 mein har state ke liye pulses ka total area kitna tha?",
         sql=f"SELECT s.state_name, SUM(p.area_hectares) FROM {P} {CAT} {ST} WHERE cc.category_name = 'Pulses' AND p.year = 2015 GROUP BY s.state_name"),
    dict(cat="group",
         en="For each season, how many production records were reported in 2015?",
         hi="2015 में हर मौसम के लिए कितने उत्पादन रिकॉर्ड दर्ज हुए?",
         te="2015లో ప్రతి సీజన్‌కు ఎన్ని ఉత్పత్తి రికార్డులు నమోదయ్యాయి?",
         hinglish="2015 mein har season ke liye kitne production records the?",
         sql=f"SELECT se.season_name, COUNT(*) FROM {P} {SE} WHERE p.year = 2015 GROUP BY se.season_name"),
    dict(cat="group",
         en="For each crop category, how many crops are there?",
         hi="हर फसल श्रेणी के लिए कितनी फसलें हैं?",
         te="ప్రతి పంట వర్గానికి ఎన్ని పంటలు ఉన్నాయి?",
         hinglish="Har crop category ke liye kitni crops hain?",
         sql="SELECT cc.category_name, COUNT(*) FROM crops c JOIN crop_categories cc ON c.category_id = cc.category_id GROUP BY cc.category_name"),
    dict(cat="group",
         en="For each state, how many districts are there?",
         hi="हर राज्य के लिए कितने जिले हैं?",
         te="ప్రతి రాష్ట్రానికి ఎన్ని జిల్లాలు ఉన్నాయి?",
         hinglish="Har state ke liye kitne districts hain?",
         sql="SELECT s.state_name, COUNT(*) FROM districts d JOIN states s ON d.state_id = s.state_id GROUP BY s.state_name"),
    dict(cat="group",
         en="For each year between 2010 and 2015, what was the average yield per hectare of rice in Andhra Pradesh?",
         hi="2010 से 2015 के बीच हर वर्ष के लिए आंध्र प्रदेश में चावल की प्रति हेक्टेयर औसत उपज कितनी थी?",
         te="2010 నుండి 2015 వరకు ప్రతి సంవత్సరానికి ఆంధ్రప్రదేశ్‌లో వరి సగటు దిగుబడి హెక్టారుకు ఎంత?",
         hinglish="2010 se 2015 ke beech har year ke liye Andhra Pradesh mein rice ki average yield kitni thi?",
         sql=f"SELECT p.year, AVG(p.yield_per_hectare) FROM {P} {CR} {ST} WHERE c.crop_name = 'Rice' AND s.state_name = 'Andhra Pradesh' AND p.year >= 2010 AND p.year <= 2015 GROUP BY p.year"),
    dict(cat="group",
         en="For each crop in the Oilseeds category, what was the total production in Rajasthan in 2015?",
         hi="2015 में राजस्थान में तिलहन श्रेणी की हर फसल के लिए कुल उत्पादन कितना था?",
         te="2015లో రాజస్థాన్‌లో నూనెగింజల వర్గంలోని ప్రతి పంటకు మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2015 mein Rajasthan mein Oilseeds category ki har crop ke liye total production kitna tha?",
         sql=f"SELECT c.crop_name, SUM(p.production_quantity) FROM {P} {CAT} {ST} WHERE cc.category_name = 'Oilseeds' AND s.state_name = 'Rajasthan' AND p.year = 2015 GROUP BY c.crop_name"),
    dict(cat="group",
         en="For each state, what was the maximum yield per hectare of sugarcane in 2015?",
         hi="2015 में हर राज्य के लिए गन्ने की अधिकतम प्रति हेक्टेयर उपज कितनी थी?",
         te="2015లో ప్రతి రాష్ట్రానికి చెరకు గరిష్ఠ దిగుబడి హెక్టారుకు ఎంత?",
         hinglish="2015 mein har state ke liye sugarcane ki maximum yield kitni thi?",
         sql=f"SELECT s.state_name, MAX(p.yield_per_hectare) FROM {P} {CR} {ST} WHERE c.crop_name = 'Sugarcane' AND p.year = 2015 GROUP BY s.state_name"),
    dict(cat="group",
         en="For each district of Kerala, what was the total area under black pepper in 2015?",
         hi="2015 में केरल के हर जिले के लिए काली मिर्च का कुल क्षेत्रफल कितना था?",
         te="2015లో కేరళలోని ప్రతి జిల్లాకు మిరియాల మొత్తం సాగు విస్తీర్ణం ఎంత?",
         hinglish="2015 mein Kerala ke har district ke liye black pepper ka total area kitna tha?",
         sql=f"SELECT d.district_name, SUM(p.area_hectares) FROM {P} {CR} {ST} WHERE c.crop_name = 'Black Pepper' AND s.state_name = 'Kerala' AND p.year = 2015 GROUP BY d.district_name"),
    dict(cat="group",
         en="For each season, what was the total maize production in Bihar in 2015?",
         hi="2015 में बिहार में हर मौसम के लिए मक्का का कुल उत्पादन कितना था?",
         te="2015లో బీహార్‌లో ప్రతి సీజన్‌కు మొక్కజొన్న మొత్తం ఉత్పత్తి ఎంత?",
         hinglish="2015 mein Bihar mein har season ke liye maize ka total production kitna tha?",
         sql=f"SELECT se.season_name, SUM(p.production_quantity) FROM {P} {CR} {ST} {SE} WHERE c.crop_name = 'Maize' AND s.state_name = 'Bihar' AND p.year = 2015 GROUP BY se.season_name"),
    dict(cat="group",
         en="For each crop category, what was the average yield per hectare across India in 2018?",
         hi="2018 में पूरे भारत में हर फसल श्रेणी के लिए प्रति हेक्टेयर औसत उपज कितनी थी?",
         te="2018లో భారతదేశం మొత్తంలో ప్రతి పంట వర్గానికి సగటు దిగుబడి హెక్టారుకు ఎంత?",
         hinglish="2018 mein poore India mein har crop category ke liye average yield kitni thi?",
         sql=f"SELECT cc.category_name, AVG(p.yield_per_hectare) FROM {P} {CAT} WHERE p.year = 2018 GROUP BY cc.category_name"),
    dict(cat="group",
         en="For each crop in the Fibres category, what was the total area across India in 2015?",
         hi="2015 में पूरे भारत में रेशा श्रेणी की हर फसल के लिए कुल क्षेत्रफल कितना था?",
         te="2015లో భారతదేశం మొత్తంలో నార పంటల వర్గంలోని ప్రతి పంటకు మొత్తం విస్తీర్ణం ఎంత?",
         hinglish="2015 mein poore India mein Fibres category ki har crop ke liye total area kitna tha?",
         sql=f"SELECT c.crop_name, SUM(p.area_hectares) FROM {P} {CAT} WHERE cc.category_name = 'Fibres' AND p.year = 2015 GROUP BY c.crop_name"),

    # ---------------- topk: GROUP BY + ORDER BY + LIMIT ----------------
    dict(cat="topk",
         en="Which 5 states produced the most wheat in 2015, and how much did each produce?",
         hi="2015 में सबसे अधिक गेहूं उत्पादन करने वाले 5 राज्य कौन से थे, और हर एक ने कितना उत्पादन किया?",
         te="2015లో అత్యధికంగా గోధుమ ఉత్పత్తి చేసిన 5 రాష్ట్రాలు ఏవి, ఒక్కొక్కటి ఎంత ఉత్పత్తి చేసింది?",
         hinglish="2015 mein sabse zyada wheat produce karne wale 5 states kaun se the, aur har ek ne kitna produce kiya?",
         sql=f"SELECT s.state_name, SUM(p.production_quantity) AS total FROM {P} {CR} {ST} WHERE c.crop_name = 'Wheat' AND p.year = 2015 GROUP BY s.state_name ORDER BY total DESC LIMIT 5"),
    dict(cat="topk",
         en="Which 3 districts of Uttar Pradesh had the highest sugarcane production in 2015, and how much?",
         hi="2015 में उत्तर प्रदेश के किन 3 जिलों में गन्ने का उत्पादन सबसे अधिक था, और कितना?",
         te="2015లో ఉత్తర ప్రదేశ్‌లో చెరకు ఉత్పత్తి అత్యధికంగా ఉన్న 3 జిల్లాలు ఏవి, ఎంత?",
         hinglish="2015 mein Uttar Pradesh ke kaun se 3 districts mein sugarcane production sabse zyada tha, aur kitna?",
         sql=f"SELECT d.district_name, SUM(p.production_quantity) AS total FROM {P} {CR} {ST} WHERE c.crop_name = 'Sugarcane' AND s.state_name = 'Uttar Pradesh' AND p.year = 2015 GROUP BY d.district_name ORDER BY total DESC LIMIT 3"),
    dict(cat="topk",
         en="Which 5 crops covered the largest total area in Maharashtra in 2015, and what was the area of each?",
         hi="2015 में महाराष्ट्र में सबसे अधिक कुल क्षेत्रफल वाली 5 फसलें कौन सी थीं, और हर एक का क्षेत्रफल कितना था?",
         te="2015లో మహారాష్ట్రలో అత్యధిక మొత్తం విస్తీర్ణంలో సాగైన 5 పంటలు ఏవి, ఒక్కొక్క దాని విస్తీర్ణం ఎంత?",
         hinglish="2015 mein Maharashtra mein sabse zyada total area wali 5 crops kaun si thi, aur har ek ka area kitna tha?",
         sql=f"SELECT c.crop_name, SUM(p.area_hectares) AS total FROM {P} {CR} {ST} WHERE s.state_name = 'Maharashtra' AND p.year = 2015 GROUP BY c.crop_name ORDER BY total DESC LIMIT 5"),
    dict(cat="topk",
         en="Which 3 years had the highest total rice production in West Bengal, and what were the totals?",
         hi="पश्चिम बंगाल में किन 3 वर्षों में चावल का कुल उत्पादन सबसे अधिक था, और कितना था?",
         te="పశ్చిమ బెంగాల్‌లో వరి మొత్తం ఉత్పత్తి అత్యధికంగా ఉన్న 3 సంవత్సరాలు ఏవి, ఎంత?",
         hinglish="West Bengal mein kaun se 3 years mein rice ka total production sabse zyada tha, aur kitna?",
         sql=f"SELECT p.year, SUM(p.production_quantity) AS total FROM {P} {CR} {ST} WHERE c.crop_name = 'Rice' AND s.state_name = 'West Bengal' GROUP BY p.year ORDER BY total DESC LIMIT 3"),
    dict(cat="topk",
         en="Which 5 districts of Punjab had the highest average rice yield per hectare in 2015, and what was it?",
         hi="2015 में पंजाब के किन 5 जिलों में चावल की प्रति हेक्टेयर औसत उपज सबसे अधिक थी, और कितनी?",
         te="2015లో పంజాబ్‌లో వరి సగటు దిగుబడి అత్యధికంగా ఉన్న 5 జిల్లాలు ఏవి, ఎంత?",
         hinglish="2015 mein Punjab ke kaun se 5 districts mein rice ki average yield sabse zyada thi, aur kitni?",
         sql=f"SELECT d.district_name, AVG(p.yield_per_hectare) AS avg_yield FROM {P} {CR} {ST} WHERE c.crop_name = 'Rice' AND s.state_name = 'Punjab' AND p.year = 2015 GROUP BY d.district_name ORDER BY avg_yield DESC LIMIT 5"),
    dict(cat="topk",
         en="Which 3 crop categories had the largest total area in Karnataka in 2015, and what was the area?",
         hi="2015 में कर्नाटक में किन 3 फसल श्रेणियों का कुल क्षेत्रफल सबसे अधिक था, और कितना?",
         te="2015లో కర్ణాటకలో అత్యధిక మొత్తం విస్తీర్ణం ఉన్న 3 పంట వర్గాలు ఏవి, ఎంత?",
         hinglish="2015 mein Karnataka mein kaun si 3 crop categories ka total area sabse zyada tha, aur kitna?",
         sql=f"SELECT cc.category_name, SUM(p.area_hectares) AS total FROM {P} {CAT} {ST} WHERE s.state_name = 'Karnataka' AND p.year = 2015 GROUP BY cc.category_name ORDER BY total DESC LIMIT 3"),
    dict(cat="topk",
         en="Which 5 states reported the most production records in 2015, and how many each?",
         hi="2015 में किन 5 राज्यों ने सबसे अधिक उत्पादन रिकॉर्ड दर्ज किए, और हर एक ने कितने?",
         te="2015లో అత్యధిక ఉత్పత్తి రికార్డులు నమోదు చేసిన 5 రాష్ట్రాలు ఏవి, ఒక్కొక్కటి ఎన్ని?",
         hinglish="2015 mein kaun se 5 states ne sabse zyada production records report kiye, aur har ek ne kitne?",
         sql=f"SELECT s.state_name, COUNT(*) AS n FROM {P} {ST} WHERE p.year = 2015 GROUP BY s.state_name ORDER BY n DESC LIMIT 5"),
    dict(cat="topk",
         en="Which 3 seasons had the largest total cultivated area across India in 2015, and what was the area?",
         hi="2015 में पूरे भारत में किन 3 मौसमों में कुल खेती का क्षेत्रफल सबसे अधिक था, और कितना?",
         te="2015లో భారతదేశం మొత్తంలో అత్యధిక సాగు విస్తీర్ణం ఉన్న 3 సీజన్‌లు ఏవి, ఎంత?",
         hinglish="2015 mein poore India mein kaun se 3 seasons mein total area sabse zyada tha, aur kitna?",
         sql=f"SELECT se.season_name, SUM(p.area_hectares) AS total FROM {P} {SE} WHERE p.year = 2015 GROUP BY se.season_name ORDER BY total DESC LIMIT 3"),
    dict(cat="topk",
         en="Which 5 states had the largest total area under cotton in 2015, and what was the area?",
         hi="2015 में किन 5 राज्यों में कपास का कुल क्षेत्रफल सबसे अधिक था, और कितना?",
         te="2015లో పత్తి మొత్తం విస్తీర్ణం అత్యధికంగా ఉన్న 5 రాష్ట్రాలు ఏవి, ఎంత?",
         hinglish="2015 mein kaun se 5 states mein cotton ka total area sabse zyada tha, aur kitna?",
         sql=f"SELECT s.state_name, SUM(p.area_hectares) AS total FROM {P} {CR} {ST} WHERE c.crop_name = 'Cotton(Lint)' AND p.year = 2015 GROUP BY s.state_name ORDER BY total DESC LIMIT 5"),
]

if __name__ == "__main__":
    out = []
    for i, q in enumerate(Q, 1):
        out.append({
            "id": f"agri_{i:03d}",
            "category": q["cat"],
            "needs_group_by": q["cat"] in ("group", "topk"),
            "order_sensitive": False,
            "questions": {k: q[k] for k in ("en", "hi", "te", "hinglish")},
            "gold_sql": q["sql"],
        })
    path = os.path.join(os.path.dirname(__file__), "..", "data", "agri", "questions.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
    from collections import Counter
    print(f"Wrote {len(out)} questions -> {os.path.normpath(path)}",
          dict(Counter(q["category"] for q in out)))
